name: Update Dragons Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

permissions:
  contents: read

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-sa.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Google credentials
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: |
          printf '%s' "$GCP_SA_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS"
          test -s "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Run updater
        run: |
          python web_scraping/update_dragons_sheet.py
