name: Update Dragons Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

permissions:
  contents: read

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Google credentials
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: |
          printf '%s' "$GCP_SA_JSON" > "$RUNNER_TEMP/gcp-sa.json"
          test -s "$RUNNER_TEMP/gcp-sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-sa.json" >> "$GITHUB_ENV"

      - name: Run updater
        run: |
          python web_scraping/update_dragons_sheet.py
